from __future__ import annotations

import json
import os
import sqlite3
from contextlib import contextmanager
from datetime import datetime
from pathlib import Path
from typing import Any, Iterator

try:
    from dotenv import load_dotenv
except Exception:  # pragma: no cover
    def load_dotenv(*_args, **_kwargs):  # type: ignore[no-redef]
        return False


BASE_DIR = Path(__file__).resolve().parent.parent
DB_PATH = BASE_DIR / "stepout.db"
load_dotenv(BASE_DIR / ".env")
load_dotenv(BASE_DIR / "backend" / ".env")


def _resolve_database_url() -> str:
    candidate = os.getenv("DATABASE_URL", "").strip()
    if not candidate:
        return ""

    # Treat the checked-in sample backend/.env as documentation only.
    # If placeholder tokens are still present, fall back to local SQLite
    # so the Flask app can boot without a Postgres setup.
    placeholder_tokens = (
        "YOUR_PASSWORD",
        "YOUR_HOST",
        "YOUR_USER",
        "YOUR_DB",
        "<password>",
        "<host>",
    )
    if any(token in candidate for token in placeholder_tokens):
        return ""

    return candidate


DATABASE_URL = _resolve_database_url()

try:
    import psycopg  # type: ignore[import-not-found]
    from psycopg.rows import dict_row  # type: ignore[import-not-found]
except Exception:  # pragma: no cover
    psycopg = None  # type: ignore[assignment]
    dict_row = None  # type: ignore[assignment]


def _utcnow_iso() -> str:
    return datetime.now().astimezone().isoformat(timespec="seconds")


def _is_postgres() -> bool:
    return bool(DATABASE_URL) and DATABASE_URL.lower().startswith(("postgres://", "postgresql://"))


def _sql(sql: str, params: tuple[Any, ...] | None = None) -> str:
    if not _is_postgres():
        return sql
    if not params:
        return sql
    placeholders = sql.count("?")
    if placeholders != len(params):
        raise ValueError(f"SQL placeholder mismatch: expected {placeholders}, got {len(params)}")
    return sql.replace("?", "%s")


@contextmanager
def _connect() -> Iterator[Any]:
    if _is_postgres():
        if psycopg is None:
            raise RuntimeError(
                "DATABASE_URL is set for Postgres but psycopg is not installed. "
                "Run: pip install psycopg[binary]"
            )
        with psycopg.connect(DATABASE_URL, row_factory=dict_row) as connection:  # type: ignore[misc]
            yield connection
        return

    connection = sqlite3.connect(DB_PATH)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    try:
        yield connection
    finally:
        connection.close()


def init_database() -> None:
    with _connect() as connection:
        if _is_postgres():
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS trainees (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    created_at TEXT NOT NULL
                )
                """
            )
            connection.execute(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS trainees_name_lower_unique
                ON trainees (LOWER(name))
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS evaluation_runs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    trainee_id BIGINT NOT NULL REFERENCES trainees(id) ON DELETE CASCADE,
                    created_at TEXT NOT NULL,
                    overall_accuracy DOUBLE PRECISION NOT NULL,
                    correct_count BIGINT NOT NULL,
                    missed_count BIGINT NOT NULL,
                    extra_count BIGINT NOT NULL,
                    mismatch_count BIGINT NOT NULL,
                    total_gold BIGINT NOT NULL,
                    total_trainee BIGINT NOT NULL,
                    top_error_attribute TEXT,
                    top_error_count BIGINT NOT NULL DEFAULT 0,
                    timestamp_deviation_percentage DOUBLE PRECISION NOT NULL DEFAULT 0,
                    timestamp_within_tolerance_count BIGINT NOT NULL DEFAULT 0,
                    passing_error_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
                    non_passing_error_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
                    worst_half TEXT,
                    snapshot_json TEXT NOT NULL
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS run_attribute_counts (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    evaluation_run_id BIGINT NOT NULL REFERENCES evaluation_runs(id) ON DELETE CASCADE,
                    attribute_code TEXT NOT NULL,
                    gold_count BIGINT NOT NULL DEFAULT 0,
                    trainee_count BIGINT NOT NULL DEFAULT 0,
                    UNIQUE (evaluation_run_id, attribute_code)
                )
                """
            )
            connection.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_evaluation_runs_trainee_created
                ON evaluation_runs (trainee_id, created_at DESC, id DESC)
                """
            )
            connection.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_run_attribute_counts_run
                ON run_attribute_counts (evaluation_run_id)
                """
            )
        else:
            connection.executescript(
                """
                CREATE TABLE IF NOT EXISTS trainees (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL COLLATE NOCASE UNIQUE,
                    created_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS evaluation_runs (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    trainee_id INTEGER NOT NULL,
                    created_at TEXT NOT NULL,
                    overall_accuracy REAL NOT NULL,
                    correct_count INTEGER NOT NULL,
                    missed_count INTEGER NOT NULL,
                    extra_count INTEGER NOT NULL,
                    mismatch_count INTEGER NOT NULL,
                    total_gold INTEGER NOT NULL,
                    total_trainee INTEGER NOT NULL,
                    top_error_attribute TEXT,
                    top_error_count INTEGER NOT NULL DEFAULT 0,
                    timestamp_deviation_percentage REAL NOT NULL DEFAULT 0,
                    timestamp_within_tolerance_count INTEGER NOT NULL DEFAULT 0,
                    passing_error_rate REAL NOT NULL DEFAULT 0,
                    non_passing_error_rate REAL NOT NULL DEFAULT 0,
                    worst_half TEXT,
                    snapshot_json TEXT NOT NULL,
                    FOREIGN KEY (trainee_id) REFERENCES trainees(id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS run_attribute_counts (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    evaluation_run_id INTEGER NOT NULL,
                    attribute_code TEXT NOT NULL,
                    gold_count INTEGER NOT NULL DEFAULT 0,
                    trainee_count INTEGER NOT NULL DEFAULT 0,
                    FOREIGN KEY (evaluation_run_id) REFERENCES evaluation_runs(id) ON DELETE CASCADE,
                    UNIQUE (evaluation_run_id, attribute_code)
                );

                CREATE INDEX IF NOT EXISTS idx_evaluation_runs_trainee_created
                ON evaluation_runs (trainee_id, created_at DESC, id DESC);

                CREATE INDEX IF NOT EXISTS idx_run_attribute_counts_run
                ON run_attribute_counts (evaluation_run_id);
                """
            )


def _serialize_snapshot(result: dict) -> str:
    snapshot = {
        "overall_accuracy": result.get("overall_accuracy", 0),
        "correct": result.get("correct", 0),
        "missed_count": result.get("missed_count", 0),
        "extra_count": result.get("extra_count", 0),
        "mismatch_count": result.get("mismatch_count", 0),
        "total_gold": result.get("total_gold", 0),
        "total_trainee": result.get("total_trainee", 0),
        "field_errors": result.get("field_errors", {}),
        "timeline_chart": result.get("timeline_chart", {}),
        "attribute_comparison": result.get("attribute_comparison", {}),
        "attribute_note_breakdown": result.get("attribute_note_breakdown", {}),
        "attribute_team_breakdown": result.get("attribute_team_breakdown", {}),
        "attribute_team_note_breakdown": result.get("attribute_team_note_breakdown", {}),
        "insights": result.get("insights", {}),
        "timestamp_within_tolerance_count": result.get("timestamp_within_tolerance_count", 0),
        "gold_count_skipped": result.get("gold_count_skipped", 0),
        "trainee_count_skipped": result.get("trainee_count_skipped", 0),
        "trainee_count_skipped_valid": result.get("trainee_count_skipped_valid", 0),
    }
    return json.dumps(snapshot, separators=(",", ":"), ensure_ascii=False)


def _normalize_trainee_name(name: str) -> str:
    return " ".join(str(name or "").split()).strip()


def get_trainee(trainee_id: int) -> dict | None:
    with _connect() as connection:
        row = connection.execute(
            _sql("SELECT id, name, created_at FROM trainees WHERE id = ?", (trainee_id,)),
            (trainee_id,),
        ).fetchone()
    return dict(row) if row else None


def list_trainees() -> list[dict]:
    with _connect() as connection:
        rows = connection.execute(
            """
            SELECT
                t.id,
                t.name,
                t.created_at,
                COUNT(r.id) AS run_count,
                ROUND(COALESCE(AVG(r.overall_accuracy), 0), 2) AS average_accuracy,
                MAX(r.created_at) AS latest_run_at,
                (
                    SELECT r2.overall_accuracy
                    FROM evaluation_runs r2
                    WHERE r2.trainee_id = t.id
                    ORDER BY r2.created_at DESC, r2.id DESC
                    LIMIT 1
                ) AS latest_accuracy
            FROM trainees t
            LEFT JOIN evaluation_runs r ON r.trainee_id = t.id
            GROUP BY t.id, t.name, t.created_at
            ORDER BY LOWER(t.name) ASC
            """
        ).fetchall()

    return [
        {
            "id": row["id"],
            "name": row["name"],
            "created_at": row["created_at"],
            "run_count": int(row["run_count"] or 0),
            "average_accuracy": float(row["average_accuracy"] or 0),
            "latest_run_at": row["latest_run_at"],
            "latest_accuracy": float(row["latest_accuracy"] or 0) if row["latest_accuracy"] is not None else None,
        }
        for row in rows
    ]


def create_trainee(name: str) -> tuple[dict, bool]:
    normalized_name = _normalize_trainee_name(name)
    if not normalized_name:
        raise ValueError("Trainee name is required.")

    with _connect() as connection:
        if _is_postgres():
            existing = connection.execute(
                _sql("SELECT id, name, created_at FROM trainees WHERE LOWER(name) = LOWER(?)", (normalized_name,)),
                (normalized_name,),
            ).fetchone()
        else:
            existing = connection.execute(
                "SELECT id, name, created_at FROM trainees WHERE name = ?",
                (normalized_name,),
            ).fetchone()
        if existing:
            return dict(existing), False

        created_at = _utcnow_iso()
        if _is_postgres():
            trainee = connection.execute(
                _sql(
                    "INSERT INTO trainees (name, created_at) VALUES (?, ?) RETURNING id, name, created_at",
                    (normalized_name, created_at),
                ),
                (normalized_name, created_at),
            ).fetchone()
        else:
            cursor = connection.execute(
                "INSERT INTO trainees (name, created_at) VALUES (?, ?)",
                (normalized_name, created_at),
            )
            trainee = connection.execute(
                "SELECT id, name, created_at FROM trainees WHERE id = ?",
                (cursor.lastrowid,),
            ).fetchone()

    return dict(trainee), True


def save_evaluation_run(trainee_id: int, result: dict) -> int:
    insights = result.get("insights", {}) or {}
    top_error_attribute = insights.get("most_error_attribute", {}) or {}
    timestamp_deviation = insights.get("timestamp_deviation", {}) or {}
    passing_error = insights.get("passing_error_prone", {}) or {}
    half_mistakes = insights.get("half_mistakes", {}) or {}
    attribute_comparison = result.get("attribute_comparison", {}) or {}
    labels = attribute_comparison.get("labels", []) or []
    gold_values = attribute_comparison.get("gold_values", []) or []
    trainee_values = attribute_comparison.get("trainee_values", []) or []

    created_at = _utcnow_iso()
    snapshot_json = _serialize_snapshot(result)

    with _connect() as connection:
        insert_sql = """
        INSERT INTO evaluation_runs (
            trainee_id,
            created_at,
            overall_accuracy,
            correct_count,
            missed_count,
            extra_count,
            mismatch_count,
            total_gold,
            total_trainee,
            top_error_attribute,
            top_error_count,
            timestamp_deviation_percentage,
            timestamp_within_tolerance_count,
            passing_error_rate,
            non_passing_error_rate,
            worst_half,
            snapshot_json
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """
        insert_params = (
            trainee_id,
            created_at,
            float(result.get("overall_accuracy", 0) or 0),
            int(result.get("correct", 0) or 0),
            int(result.get("missed_count", 0) or 0),
            int(result.get("extra_count", 0) or 0),
            int(result.get("mismatch_count", 0) or 0),
            int(result.get("total_gold", 0) or 0),
            int(result.get("total_trainee", 0) or 0),
            top_error_attribute.get("attribute"),
            int(top_error_attribute.get("count", 0) or 0),
            float(timestamp_deviation.get("percentage", 0) or 0),
            int(result.get("timestamp_within_tolerance_count", 0) or 0),
            float(passing_error.get("passing_error_rate", 0) or 0),
            float(passing_error.get("non_passing_error_rate", 0) or 0),
            half_mistakes.get("worst_half"),
            snapshot_json,
        )

        if _is_postgres():
            row = connection.execute(
                _sql(insert_sql + " RETURNING id", insert_params),
                insert_params,
            ).fetchone()
            evaluation_run_id = int(row["id"])
        else:
            cursor = connection.execute(insert_sql, insert_params)
            evaluation_run_id = int(cursor.lastrowid)

        metric_rows = []
        for index, label in enumerate(labels):
            metric_rows.append(
                (
                    evaluation_run_id,
                    str(label),
                    int(gold_values[index] if index < len(gold_values) else 0),
                    int(trainee_values[index] if index < len(trainee_values) else 0),
                )
            )

        if metric_rows:
            insert_metrics_sql = """
            INSERT INTO run_attribute_counts (
                evaluation_run_id,
                attribute_code,
                gold_count,
                trainee_count
            ) VALUES (?, ?, ?, ?)
            """
            if _is_postgres():
                connection.executemany(_sql(insert_metrics_sql, metric_rows[0]), metric_rows)
            else:
                connection.executemany(insert_metrics_sql, metric_rows)

    return evaluation_run_id


def _fetch_run_attribute_counts(connection: Any, evaluation_run_id: int) -> list[dict]:
    rows = connection.execute(
        _sql(
            """
            SELECT attribute_code, gold_count, trainee_count
            FROM run_attribute_counts
            WHERE evaluation_run_id = ?
            ORDER BY attribute_code ASC
            """,
            (evaluation_run_id,),
        ),
        (evaluation_run_id,),
    ).fetchall()

    metrics = []
    for row in rows:
        delta = int(row["trainee_count"] or 0) - int(row["gold_count"] or 0)
        metrics.append(
            {
                "attribute": row["attribute_code"],
                "gold_count": int(row["gold_count"] or 0),
                "trainee_count": int(row["trainee_count"] or 0),
                "delta": delta,
                "absolute_gap": abs(delta),
            }
        )
    return metrics


def _build_ai_report(trainee_name: str, latest_run: dict | None, previous_run: dict | None, latest_attribute_gaps: list[dict], total_runs: int, average_accuracy: float) -> dict:
    if not latest_run:
        return {
            "title": "No report history yet",
            "summary": f"{trainee_name} does not have any saved evaluation runs yet.",
            "bullets": [
                "Run one evaluation to start building the trainee progress history.",
            ],
        }

    latest_accuracy = float(latest_run.get("overall_accuracy", 0) or 0)
    latest_top_attribute = latest_run.get("top_error_attribute") or "N/A"
    latest_gap = latest_attribute_gaps[0]["attribute"] if latest_attribute_gaps else None
    latest_timestamp = float(latest_run.get("timestamp_deviation_percentage", 0) or 0)

    if previous_run:
        previous_accuracy = float(previous_run.get("overall_accuracy", 0) or 0)
        accuracy_delta = round(latest_accuracy - previous_accuracy, 2)
        if accuracy_delta > 0:
            trajectory = f"improved by {accuracy_delta:.2f} percentage points compared with the previous run."
        elif accuracy_delta < 0:
            trajectory = f"dropped by {abs(accuracy_delta):.2f} percentage points compared with the previous run."
        else:
            trajectory = "held the same accuracy as the previous run."
    else:
        accuracy_delta = None
        trajectory = "is establishing the first saved benchmark."

    bullets = [
        f"Latest accuracy is {latest_accuracy:.2f}% across {int(latest_run.get('total_gold', 0) or 0):,} gold events.",
        f"Current recurring error pressure is highest around {latest_top_attribute}." if latest_top_attribute and latest_top_attribute != "N/A" else "No dominant error attribute has appeared yet.",
        f"Timestamp deviation is currently {latest_timestamp:.2f}%." if latest_timestamp else "Timestamp deviation is currently controlled.",
    ]

    if latest_gap:
        bullets.append(f"The largest latest volume gap is on {latest_gap}, which is a good candidate for focused feedback.")
    if total_runs > 1:
        bullets.append(f"Average accuracy across {total_runs} saved runs is {average_accuracy:.2f}%.")

    summary = f"{trainee_name} {trajectory}"

    return {
        "title": "AI Progress Readout",
        "summary": summary,
        "bullets": bullets,
        "accuracy_delta": accuracy_delta,
    }


def get_progress_report(trainee_id: int, history_limit: int = 12) -> dict | None:
    with _connect() as connection:
        trainee = connection.execute(
            _sql("SELECT id, name, created_at FROM trainees WHERE id = ?", (trainee_id,)),
            (trainee_id,),
        ).fetchone()
        if not trainee:
            return None

        rows = connection.execute(
            _sql(
                """
                SELECT
                    id,
                    trainee_id,
                    created_at,
                    overall_accuracy,
                    correct_count,
                    missed_count,
                    extra_count,
                    mismatch_count,
                    total_gold,
                    total_trainee,
                    top_error_attribute,
                    top_error_count,
                    timestamp_deviation_percentage,
                    timestamp_within_tolerance_count,
                    passing_error_rate,
                    non_passing_error_rate,
                    worst_half
                FROM evaluation_runs
                WHERE trainee_id = ?
                ORDER BY created_at DESC, id DESC
                """,
                (trainee_id,),
            ),
            (trainee_id,),
        ).fetchall()

        runs = [dict(row) for row in rows]
        latest_run = runs[0] if runs else None
        previous_run = runs[1] if len(runs) > 1 else None
        latest_attribute_gaps = _fetch_run_attribute_counts(connection, latest_run["id"]) if latest_run else []
        latest_attribute_gaps.sort(key=lambda item: (item["absolute_gap"], item["attribute"]), reverse=True)
        latest_attribute_gaps = latest_attribute_gaps[:8]

    total_runs = len(runs)
    average_accuracy = round(
        sum(float(run["overall_accuracy"] or 0) for run in runs) / total_runs,
        2,
    ) if total_runs else 0.0
    best_accuracy = round(max((float(run["overall_accuracy"] or 0) for run in runs), default=0.0), 2)
    latest_accuracy = round(float(latest_run["overall_accuracy"] or 0), 2) if latest_run else 0.0
    previous_accuracy = round(float(previous_run["overall_accuracy"] or 0), 2) if previous_run else None
    accuracy_delta = round(latest_accuracy - previous_accuracy, 2) if previous_run else None

    history_rows = []
    for index, run in enumerate(runs[:history_limit], start=1):
        history_rows.append(
            {
                "run_id": int(run["id"]),
                "sequence": index,
                "created_at": run["created_at"],
                "overall_accuracy": round(float(run["overall_accuracy"] or 0), 2),
                "correct_count": int(run["correct_count"] or 0),
                "missed_count": int(run["missed_count"] or 0),
                "extra_count": int(run["extra_count"] or 0),
                "mismatch_count": int(run["mismatch_count"] or 0),
                "total_gold": int(run["total_gold"] or 0),
                "total_trainee": int(run["total_trainee"] or 0),
                "top_error_attribute": run["top_error_attribute"] or "N/A",
                "top_error_count": int(run["top_error_count"] or 0),
                "timestamp_deviation_percentage": round(float(run["timestamp_deviation_percentage"] or 0), 2),
                "passing_error_rate": round(float(run["passing_error_rate"] or 0), 2),
                "non_passing_error_rate": round(float(run["non_passing_error_rate"] or 0), 2),
                "worst_half": run["worst_half"] or "N/A",
            }
        )

    chart_runs = list(reversed(history_rows))
    accuracy_trend = {
        "labels": [f"Run {row['sequence']}" for row in reversed(history_rows)],
        "values": [row["overall_accuracy"] for row in chart_runs],
    }

    return {
        "trainee": dict(trainee),
        "overview": {
            "total_runs": total_runs,
            "average_accuracy": average_accuracy,
            "latest_accuracy": latest_accuracy,
            "previous_accuracy": previous_accuracy,
            "accuracy_delta": accuracy_delta,
            "best_accuracy": best_accuracy,
            "latest_run_at": latest_run["created_at"] if latest_run else None,
            "latest_mismatch_count": int(latest_run["mismatch_count"] or 0) if latest_run else 0,
        },
        "accuracy_trend": accuracy_trend,
        "latest_attribute_gaps": latest_attribute_gaps,
        "history": history_rows,
        "ai_report": _build_ai_report(
            trainee_name=trainee["name"],
            latest_run=latest_run,
            previous_run=previous_run,
            latest_attribute_gaps=latest_attribute_gaps,
            total_runs=total_runs,
            average_accuracy=average_accuracy,
        ),
    }
